### ISSUE TITLE
dataset for  pre-trained weight

### ISSUE THREAD

**Issue by zwang573** [cure-lab/MagicDrive#96]
Thanks for your amazing work!
Do we have to download and process the full nuscenes dataset if we just want use the pretrained weight for video generation?

**Comment by flymin** [comment]
You can check the demo with the webui first. They have minimal dependencies.

**Comment by zwang573** [comment]
yes we tried webui and the demo for image generation, the run.py script works pretty good but we got errors when we try to use the webui.

**Comment by zwang573** [comment]
<img width="754" alt="Screenshot 2024-10-21 at 1 27 52 AM" src="https://github.com/user-attachments/assets/fdfcc687-bae2-4a44-ab3b-66bceba12d69">

following is the detail of the error message:

`(magicdrive) root@zw-gs-67fc776784-khnh7:/home/user/persistent/MagicDrive# python demo/interactive_gui.py
/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/diffusers/utils/import_utils.py:226: UserWarning: PyTorch should be >= 1.12
  warnings.warn("PyTorch should be >= 1.12")
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
IMPORTANT: You are using gradio version 4.16.0, however version 4.44.1 is available, please upgrade.
--------
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 658, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 883, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/_compat.py", line 658, in get_cached_model_fields
    return get_model_fields(model)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 5, in __init__
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/home/user/persistent/miniconda3/envs/magicdrive/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.`

**Comment by flymin** [comment]
https://github.com/oobabooga/text-generation-webui/issues/6367 is this related?

**Comment by 19834866823** [comment]
> [oobabooga/text-generation-webui#6367](https://github.com/oobabooga/text-generation-webui/issues/6367) is this related?

Thanks, very helpful! I had this problem as well, and it was solved after lowering the version according to the link you provided!
 Executing the following three  commands solved my problem.
    pip install --upgrade pydantic==2.8.2
    pip install --upgrade pydantic-core==2.20.1
    pip install --upgrade fastapi==0.112.4
